name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Push backend
        run: |
          docker build -t yourdocker/backend ./backend
          docker push yourdocker/backend
      - name: Build and Push frontend
        run: |
          docker build -t yourdocker/frontend ./frontend
          docker push yourdocker/frontend
