name: CI/CD Pipeline - Full App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push backend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend ./docker-devops-app/backend
        docker push ${{ secrets.DOCKER_USERNAME }}/backend

    - name: Build & Push frontend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend ./docker-devops-app/frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "Stopping existing containers..."
          docker-compose -f ~/DevStack-Lite/docker-devops-app/docker-compose.yml down || true

          echo "Pruning old Docker images and volumes..."
          docker image prune -a -f || true
          docker volume prune -f || true

          echo "Removing old code..."
          rm -rf ~/DevStack-Lite || true

          echo "Pulling updated images from DockerHub..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/backend
          docker pull ${{ secrets.DOCKER_USERNAME }}/frontend

          echo "Cloning fresh repo..."
          git clone https://github.com/saikrupaelate/DevStack-Lite.git ~/DevStack-Lite

          echo "Starting containers..."
          cd ~/DevStack-Lite/docker-devops-app
          docker-compose up -d
